from server.routes.telephonist.application_api import application_api_router
from server.routes.telephonist.user_api import user_api_application
from server.routes.telephonist.ws_root_router import ws_root_router
